FROM node:20-alpine
WORKDIR /usr/src/app
COPY package*.json ./
# O npm install falhará agora pois não há package.json, 
# mas criaremos os projetos na sequência.
RUN touch package.json
EXPOSE 3000 5173
CMD ["sh", "-c", "echo 'Container rodando. Aguardando inicialização do framework...' && tail -f /dev/null"]